import { make, notice, page, table } from '../../shared/view-helpers.mjs';
import { managementRequest, showOneTimeSecret, typedConfirmation } from '../../shared/management-actions.mjs';

export async function renderRoute(context) {
  const data = await managementRequest('/api/management/api-keys'); if (!context.isCurrent()) return; const view = page('API keys', 'Create scoped credentials, disclose material once, rotate with bounded overlap, or revoke after recent reauthentication and typed confirmation.');
  const feedback = make('div'); feedback.setAttribute('role', 'status'); const form = make('form'); const name = make('input'); name.required = true; name.name = 'name'; const scopes = make('input'); scopes.name = 'scopes'; scopes.value = 'config:read'; const create = make('button', 'Create API key'); form.append(make('label', 'Key name'), name, make('label', 'Scopes (comma-separated)'), scopes, create);
  form.addEventListener('submit', async (event) => { event.preventDefault(); create.disabled = true; try { const result = await managementRequest('/api/management/api-keys', { method: 'POST', body: { name: name.value, scopes: scopes.value.split(',').map((item) => item.trim()).filter(Boolean) } }); showOneTimeSecret({ secret: result.disclosure.secret, opener: create, onClose: () => { feedback.textContent = 'The one-time disclosure was cleared.'; void context.refresh(); } }); } catch (error) { feedback.replaceChildren(notice(error.message, { error: true })); } finally { create.disabled = false; } });
  const rows = data.keys.map((key) => { const rotate = make('button', 'Rotate'); rotate.type = 'button'; rotate.addEventListener('click', async () => { const result = await managementRequest(`/api/management/api-keys/${encodeURIComponent(key.id)}/rotate`, { method: 'POST', body: { overlapMs: 3600000 } }); showOneTimeSecret({ secret: result.disclosure.secret, opener: rotate, onClose: () => void context.refresh() }); }); const revoke = make('button', 'Revoke'); revoke.type = 'button'; revoke.addEventListener('click', () => typedConfirmation({ title: `Revoke ${key.name}`, instruction: `Type REVOKE ${key.name} after you have reauthenticated.`, confirmLabel: 'Revoke key', opener: revoke, onConfirm: async (value) => { await managementRequest(`/api/management/api-keys/${encodeURIComponent(key.id)}/revoke`, { method: 'POST', body: { confirmation: value } }); feedback.textContent = 'Key revoked.'; void context.refresh(); } })); return [key.name, key.scopes.join(', '), key.active ? 'Active' : 'Revoked', rotate, revoke]; });
  view.node.append(form, feedback, rows.length ? table(['Name', 'Scopes', 'State', 'Rotate', 'Revoke'], rows, 'Scoped API keys') : notice('No API keys exist in this scope.')); context.root.replaceChildren(view.node);
}
