import { make, link, notice, page, table } from '../../shared/view-helpers.mjs';
import { managementRequest } from '../../shared/management-actions.mjs';

export async function renderRoute(context) {
  const data = await managementRequest('/api/management/providers'); if (!context.isCurrent()) return; const view = page('Integrations', 'Provider configuration and tests are authorized and scoped by the server; submitted credentials are never retained in this page.'); const feedback = make('div'); feedback.setAttribute('role', 'status'); feedback.textContent = data.correlationId ? `Support correlation: ${data.correlationId}` : '';
  const form = make('form'); const provider = make('input'); provider.required = true; const credential = make('input'); credential.type = 'password'; credential.autocomplete = 'off'; const submit = make('button', 'Add provider'); form.append(make('label', 'Provider'), provider, make('label', 'Credential'), credential, submit);
  form.addEventListener('submit', async (event) => { event.preventDefault(); try { const result = await managementRequest('/api/management/providers', { method: 'POST', body: { provider: provider.value, credential: credential.value } }); credential.value = ''; feedback.textContent = `Provider saved. Support correlation: ${result.correlationId}`; void context.refresh(); } catch (error) { credential.value = ''; feedback.replaceChildren(notice(error.message, { error: true })); } });
  const rows = data.providers.map((item) => [link(`/app/integrations/providers/${encodeURIComponent(item.id)}`, item.name), item.status, item.enabled ? 'Enabled' : 'Disabled', String(item.revision)]); view.node.append(form, feedback, rows.length ? table(['Provider', 'Status', 'State', 'Revision'], rows, 'Scoped provider integrations') : notice('No providers are configured in this scope.')); context.root.replaceChildren(view.node);
}
