import { decideManagementAuthorization, nonDisclosingDenial } from './management-authorization.mjs';
import { appendManagementAudit, listManagementAudit, pruneManagementAudit } from './management-audit.mjs';
import { createOneTimeDisclosure, consumeOneTimeDisclosure, clearOneTimeDisclosure, generateSecretMaterial, publicCredential, safeManagementError } from './management-secrets.mjs';
import { listIntegrations, getIntegration, saveIntegration, testIntegration, integrationSnapshot, restoreIntegrationSnapshot } from './management-integrations.mjs';
import { recordWebhookAttempt, listWebhookAttempts, replayWebhookAttempt, webhookSnapshot, restoreWebhookSnapshot } from './management-webhooks.mjs';
import { explainPermissions, invite, listInvitations, updateInvitation, listMemberships, changeMembership, accessSnapshot, restoreAccessSnapshot } from './management-access.mjs';
import { getUserStore } from '../auth/user-store.mjs';
import { managementBilling } from './management-billing.mjs';
import { loadManagementState, saveManagementState } from './management-state.mjs';
import { generateApiKey, revokeApiKey, registerManagedApiKey, listManagedApiKeys } from '../auth/api-tokens.mjs';
import { randomUUID, timingSafeEqual } from 'node:crypto';

const keys = new Map(); const previews = new Map();
const reauthSessions = new Map();
// The feature's adapters keep legacy in-memory helpers, but their snapshots are durable per
// tenant. Serialize load/mutate/save so an awaited management operation can never replace a
// different tenant's snapshot while it is in flight.
let managementStateQueue = Promise.resolve();
async function acquireManagementStateLock() { let release; const previous = managementStateQueue; managementStateQueue = new Promise((resolve) => { release = resolve; }); await previous; return release; }
function freshReauthentication(actorId, token) { const session = reauthSessions.get(token); if (!session || session.actorId !== actorId || session.expiresAt < Date.now()) return false; return true; }
function hasCurrentLocalSessionProof(req, proof) { const token = String(req.headers['x-aios-token'] ?? ''); const supplied = String(proof ?? ''); if (!token || token.length !== supplied.length) return false; return timingSafeEqual(Buffer.from(token), Buffer.from(supplied)); }
function response(res, status, body) { res.writeHead(status, { 'content-type': 'application/json', 'cache-control': 'no-store', 'referrer-policy': 'no-referrer', 'content-security-policy': "default-src 'none'" }); res.end(JSON.stringify(body)); return true; }
function capability(path, method) { if (path.includes('/providers')) return method === 'GET' ? 'providersRead' : 'providersWrite'; if (path.includes('/api-keys')) return method === 'GET' ? 'keysRead' : 'keysWrite'; if (path.includes('/webhooks')) return method === 'GET' ? 'webhooksRead' : 'webhooksWrite'; if (path.includes('/access')) return method === 'GET' ? 'accessRead' : 'accessWrite'; if (path.includes('/billing')) return 'billingRead'; if (path.includes('/audit')) return 'auditRead'; return method === 'GET' ? 'accessRead' : 'settingsWrite'; }
async function bodyOf(readBody, req) { try { return JSON.parse((await readBody(req)) || '{}'); } catch { return null; } }
function audit(db, decision, intent, outcome, body, classification = 'restricted') { return appendManagementAudit(db, { decision, intent, reason: body?.reason, outcome, disclosureClassification: classification, evidence: { request: body } }); }
function publicKey(row) { return publicCredential(row); }

/** Dispatch the additive /api/management contract.  Every request is authenticated and audited. */
export async function handleManagementRequest(req, res, url, { config, db, readBody, requireAuth, dashboardAuthorized = () => false }) {
  if (!url.pathname.startsWith('/api/management/')) return false;
  // The embedded local dashboard has a per-boot, same-origin server-verified session token;
  // API clients use a verified bearer/API-key identity. Neither path trusts UI-selected scope.
  if (!req.headers.authorization && dashboardAuthorized(req)) req.user = { sub: 'local-operator', role: 'admin' };
  else if (!requireAuth(req, res)) return true;
  const body = ['POST', 'PUT', 'PATCH', 'DELETE'].includes(req.method) ? await bodyOf(readBody, req) : {};
  if (body === null) return response(res, 400, { ok: false, error: { code: 'INVALID_JSON' } });
  const decision = decideManagementAuthorization({ config, user: req.user, capability: capability(url.pathname, req.method), requestedScope: { tenantId: body.tenantId ?? url.searchParams.get('tenantId'), projectId: body.projectId ?? url.searchParams.get('projectId') } });
  if (!decision.allowed) { audit(db, decision, 'management_request', 'denied', body); return response(res, 403, nonDisclosingDenial(decision)); }
  const scope = decision.scope; const path = url.pathname; const releaseStateLock = await acquireManagementStateLock(); let stateLoaded = false;
  pruneManagementAudit(db);
  const fail = (status, outcome, intent = 'management_request') => { const event = audit(db, decision, intent, outcome, body); return response(res, status, { ok: false, outcome, correlationId: decision.correlationId, audit: { id: event.id } }); };
  try {
    const state = loadManagementState(db, scope.tenantId); keys.clear(); previews.clear(); for (const row of state.keys ?? []) keys.set(...row); for (const row of state.previews ?? []) previews.set(...row); restoreIntegrationSnapshot(state.integrations); restoreWebhookSnapshot(state.webhooks); restoreAccessSnapshot(state.access); stateLoaded = true;
    if (req.method === 'POST' && path === '/api/management/reauthenticate') {
      if (req.user.sub === 'local-operator') { if (!hasCurrentLocalSessionProof(req, body.localSessionProof)) return fail(401, 'denied', 'reauthenticate'); const token = randomUUID(); reauthSessions.set(token, { actorId: req.user.sub, expiresAt: Date.now() + 5 * 60_000 }); const event = audit(db, decision, 'reauthenticate', 'succeeded', {}); return response(res, 200, { ok: true, reauthToken: token, expiresAt: new Date(Date.now() + 5 * 60_000).toISOString(), correlationId: decision.correlationId, audit: { id: event.id } }); }
      const { getUserStore } = await import('../auth/user-store.mjs'); const account = getUserStore().getUserById(req.user.sub);
      if (!account || !getUserStore().verifyCredentials(account.email, body.password)) return fail(401, 'denied', 'reauthenticate');
      const token = randomUUID(); reauthSessions.set(token, { actorId: req.user.sub, expiresAt: Date.now() + 5 * 60_000 }); const event = audit(db, decision, 'reauthenticate', 'succeeded', body);
      return response(res, 200, { ok: true, reauthToken: token, expiresAt: new Date(Date.now() + 5 * 60_000).toISOString(), correlationId: decision.correlationId, audit: { id: event.id } });
    }
    if (req.method === 'GET' && path === '/api/management/providers') { const event = audit(db, decision, 'providers_list', 'allowed', body); return response(res, 200, { ok: true, providers: listIntegrations(scope), correlationId: decision.correlationId, audit: { id: event.id } }); }
    const provider = path.match(/^\/api\/management\/providers\/([^/]+)(?:\/(test|retry))?$/);
    if (provider && req.method === 'GET' && !provider[2]) { const row = getIntegration(provider[1], scope); if (!row) return fail(404, 'denied', 'provider_read'); const event = audit(db, decision, 'provider_read', 'allowed', body); return response(res, 200, { ok: true, provider: row, correlationId: decision.correlationId, audit: { id: event.id } }); }
    if (req.method === 'POST' && path === '/api/management/providers') { const row = saveIntegration(scope, body); const event = audit(db, decision, 'provider_create', 'succeeded', body); return response(res, 201, { ok: true, provider: row, correlationId: decision.correlationId, audit: { id: event.id } }); }
    if (provider && ['POST', 'PUT', 'PATCH'].includes(req.method)) { const row = provider[2] ? await testIntegration(provider[1], scope, { retry: provider[2] === 'retry' ? 1 : 0, credential: body.credential, runner: async (integration, { signal }) => { try { const { resolveProvider } = await import('../providers.mjs'); const { testProviderConnection } = await import('../provider-conformance.mjs'); const resolved = resolveProvider(integration.provider, {}, config); return resolved?.keyEnv ? testProviderConnection(resolved, body.credential, { signal }) : { status: 'unsupported' }; } catch { return { status: 'unknown' }; } } }) : saveIntegration(scope, { ...body, id: provider[1] }); if (!row) return fail(404, 'denied', 'provider_operation'); const event = audit(db, decision, provider[2] ? `provider_${provider[2]}` : 'provider_update', provider[2] ? (row.status === 'success' ? 'succeeded' : 'failed') : 'succeeded', body); return response(res, 200, { ok: true, result: row, correlationId: decision.correlationId, audit: { id: event.id } }); }
    if (req.method === 'GET' && path === '/api/management/api-keys') { const event = audit(db, decision, 'key_list', 'allowed', body); const rows = listManagedApiKeys(db, scope).map((row) => ({ id: row.id, name: row.name, scopes: row.scopes.split(','), active: Boolean(row.is_active), createdAt: new Date(row.created_at * 1000).toISOString(), projectId: row.project_id, replacementFor: row.replacement_for, overlapUntil: row.overlap_until ? new Date(row.overlap_until * 1000).toISOString() : null })); return response(res, 200, { ok: true, keys: rows, correlationId: decision.correlationId, audit: { id: event.id } }); }
    if (req.method === 'POST' && path === '/api/management/api-keys') { const row = generateApiKey(db, { name: String(body.name || 'API key').slice(0, 80), scopes: Array.isArray(body.scopes) ? body.scopes : [] }); registerManagedApiKey(db, { keyId: row.id, tenantId: scope.tenantId, projectId: scope.projectId }); const disclosure = createOneTimeDisclosure({ keyId: row.id, material: row.id }); const event = audit(db, decision, 'key_create', 'succeeded', body, 'secret_once'); return response(res, 201, { ok: true, key: { id: row.id, name: row.name, scopes: row.scopes.split(','), active: true }, disclosure, correlationId: decision.correlationId, audit: { id: event.id } }); }
    const keyRoute = path.match(/^\/api\/management\/api-keys\/([^/]+)(?:\/(disclose|close|rotate|revoke))?$/);
    if (keyRoute && keyRoute[2] === 'disclose' && req.method === 'POST') { const material = consumeOneTimeDisclosure(body.nonce, keyRoute[1]); if (!material) return fail(410, 'conflict', 'key_disclose'); const event = audit(db, decision, 'key_disclose', 'succeeded', body, 'secret_once'); return response(res, 200, { ok: true, disclosure: { secret: material, expiresAt: new Date().toISOString() }, correlationId: decision.correlationId, audit: { id: event.id } }); }
    if (keyRoute && keyRoute[2] === 'close' && req.method === 'POST') { clearOneTimeDisclosure(body.nonce); const event = audit(db, decision, 'key_disclosure_close', 'cancelled', body, 'secret_once'); return response(res, 204, { ok: true, correlationId: decision.correlationId, audit: { id: event.id } }); }
    if (keyRoute && keyRoute[2] === 'rotate' && req.method === 'POST') { const old = listManagedApiKeys(db, scope).find((row) => row.id === keyRoute[1]); if (!old) return fail(404, 'denied', 'key_rotate'); const overlapMs = Math.min(86400000, Math.max(0, Number(body.overlapMs) || 3600000)); const overlapUntil = Math.floor((Date.now() + overlapMs) / 1000); const row = generateApiKey(db, { name: old.name, scopes: old.scopes }); registerManagedApiKey(db, { keyId: old.id, tenantId: scope.tenantId, projectId: scope.projectId, replacementFor: old.replacement_for, overlapUntil }); registerManagedApiKey(db, { keyId: row.id, tenantId: scope.tenantId, projectId: scope.projectId, replacementFor: old.id }); const disclosure = createOneTimeDisclosure({ keyId: row.id, material: row.id }); const event = audit(db, decision, 'key_rotate', 'succeeded', body, 'secret_once'); return response(res, 201, { ok: true, key: { id: row.id, name: row.name, scopes: row.scopes.split(','), active: true }, disclosure, previousOverlapUntil: new Date(overlapUntil * 1000).toISOString(), correlationId: decision.correlationId, audit: { id: event.id } }); }
    if (keyRoute && keyRoute[2] === 'revoke' && req.method === 'POST') { const row = listManagedApiKeys(db, scope).find((item) => item.id === keyRoute[1]); if (!row) return fail(404, 'denied', 'key_revoke'); if (body.confirmation !== `REVOKE ${row.name}` || !freshReauthentication(req.user.sub, req.headers['x-management-reauth'])) return fail(409, 'conflict', 'key_revoke'); revokeApiKey(db, row.id); const event = audit(db, decision, 'key_revoke', 'succeeded', body); return response(res, 200, { ok: true, key: { id: row.id, name: row.name, active: false }, correlationId: decision.correlationId, audit: { id: event.id } }); }
    const webhook = path.match(/^\/api\/management\/webhooks\/([^/]+)\/attempts(?:\/([^/]+)\/replay)?$/);
    if (webhook && req.method === 'GET') { const page = listWebhookAttempts(db, scope, webhook[1], { cursor: url.searchParams.get('cursor'), limit: url.searchParams.get('limit') }); const event = audit(db, decision, 'webhook_attempts_list', 'allowed', body); return response(res, 200, { ok: true, ...page, correlationId: decision.correlationId, audit: { id: event.id } }); }
    if (webhook && webhook[2] && req.method === 'POST') { const replay = await replayWebhookAttempt(db, scope, webhook[1], webhook[2], body.reason, async (attempt) => { const { replayWebhookDelivery } = await import('../api/webhooks.mjs'); return replayWebhookDelivery(db, { webhookId: webhook[1], eventType: attempt.event, data: { replayOf: attempt.id } }); }); const event = audit(db, decision, 'webhook_replay', replay.outcome, body); return response(res, replay.outcome === 'denied' ? 404 : replay.outcome === 'ineligible' ? 409 : 200, { ok: replay.outcome === 'succeeded' || replay.outcome === 'duplicate', replay, correlationId: decision.correlationId, audit: { id: event.id } }); }
    if (req.method === 'POST' && path === '/api/management/webhooks/attempts') { const row = recordWebhookAttempt(db, scope, body); if (!row) return fail(404, 'denied', 'webhook_attempt_record'); const event = audit(db, decision, 'webhook_attempt_record', 'succeeded', body); return response(res, 201, { ok: true, attempt: row, correlationId: decision.correlationId, audit: { id: event.id } }); }
    if (req.method === 'GET' && path === '/api/management/access/invitations') { const event = audit(db, decision, 'invitation_list', 'allowed', body); return response(res, 200, { ok: true, invitations: listInvitations(getUserStore(), scope), correlationId: decision.correlationId, audit: { id: event.id } }); }
    if (req.method === 'POST' && path === '/api/management/access/invitations') { const row = invite(getUserStore(), scope, body); if (!row) return fail(409, 'conflict', 'invitation_create'); const event = audit(db, decision, 'invitation_create', 'succeeded', body); return response(res, 201, { ok: true, invitation: row, correlationId: decision.correlationId, audit: { id: event.id } }); }
    const invitation = path.match(/^\/api\/management\/access\/invitations\/([^/]+)\/(resend|cancel|accept)$/);
    if (invitation && req.method === 'POST') { const row = updateInvitation(getUserStore(), scope, invitation[1], invitation[2]); if (!row) return fail(409, invitation[2] === 'accept' ? 'conflict' : 'denied', `invitation_${invitation[2]}`); const event = audit(db, decision, `invitation_${invitation[2]}`, 'succeeded', body); return response(res, 200, { ok: true, invitation: row, correlationId: decision.correlationId, audit: { id: event.id } }); }
    if (req.method === 'GET' && path === '/api/management/access/memberships') { const event = audit(db, decision, 'membership_list', 'allowed', body); return response(res, 200, { ok: true, memberships: listMemberships(getUserStore(), scope), correlationId: decision.correlationId, audit: { id: event.id } }); }
    if (req.method === 'GET' && path === '/api/management/access/effective-permissions') { const event = audit(db, decision, 'permissions_explain', 'allowed', body); return response(res, 200, { ok: true, permissions: explainPermissions({ ...scope, role: req.user.role }), correlationId: decision.correlationId, audit: { id: event.id } }); }
    const membership = path.match(/^\/api\/management\/access\/memberships\/([^/]+)$/);
    if (membership && req.method === 'PATCH') { const row = changeMembership(getUserStore(), scope, membership[1], body.role); if (!row) return fail(404, 'denied', 'membership_change'); const event = audit(db, decision, 'membership_change', 'succeeded', body); return response(res, 200, { ok: true, membership: row, correlationId: decision.correlationId, audit: { id: event.id } }); }
    if (req.method === 'GET' && path === '/api/management/billing') { const event = audit(db, decision, 'billing_read', 'allowed', body); return response(res, 200, { ok: true, billing: managementBilling(scope, config), correlationId: decision.correlationId, audit: { id: event.id } }); }
    if (req.method === 'POST' && path === '/api/management/settings/policy/preview') { const { migrateCloudDb, previewPolicyPush } = await import('../cloud/cloud-control-plane.mjs'); migrateCloudDb(db); if (!db.prepare('SELECT id FROM cloud_organizations WHERE id = ?').get(scope.tenantId)) db.prepare('INSERT INTO cloud_organizations (id, name, created_at, is_active) VALUES (?, ?, ?, 1)').run(scope.tenantId, scope.tenantId, Date.now()); const preview = previewPolicyPush(db, scope.tenantId, body.updates, { actor: req.user.sub }); const event = audit(db, decision, 'policy_preview', 'succeeded', body); return response(res, 200, { ok: true, preview, correlationId: decision.correlationId, audit: { id: event.id } }); }
    const policy = path.match(/^\/api\/management\/settings\/policy\/([^/]+)\/(confirm|rollback)$/);
    if (policy && req.method === 'POST') { const { migrateCloudDb, confirmPolicyPush, rollbackPolicyPush } = await import('../cloud/cloud-control-plane.mjs'); migrateCloudDb(db); const reauth = freshReauthentication(req.user.sub, req.headers['x-management-reauth']); if (!reauth) return fail(409, 'conflict', `policy_${policy[2]}`); let result; try { result = policy[2] === 'confirm' ? confirmPolicyPush(db, policy[1], { actor: req.user.sub, authenticatedAt: Date.now(), confirmation: body.confirmation }) : rollbackPolicyPush(db, policy[1], { actor: req.user.sub, authenticatedAt: Date.now() }); } catch { return fail(404, 'denied', `policy_${policy[2]}`); } const event = audit(db, decision, `policy_${policy[2]}`, result.outcome, body); return response(res, 200, { ok: true, result, correlationId: decision.correlationId, audit: { id: event.id } }); }
    if (req.method === 'GET' && path === '/api/management/audit') { const page = listManagementAudit(db, scope, { cursor: url.searchParams.get('cursor'), limit: url.searchParams.get('limit') }); return response(res, 200, { ok: true, ...page, correlationId: decision.correlationId }); }
    return response(res, 404, { ok: false, error: { code: 'MANAGEMENT_NOT_FOUND', correlationId: decision.correlationId } });
  } catch { const event = audit(db, decision, 'management_request', 'failed', body); return response(res, 500, { ok: false, error: safeManagementError(), correlationId: decision.correlationId, audit: { id: event.id } }); }
  finally { try { if (stateLoaded) saveManagementState(db, scope.tenantId, { keys: [...keys.entries()], previews: [...previews.entries()], integrations: integrationSnapshot(), webhooks: webhookSnapshot(), access: accessSnapshot() }); } finally { releaseStateLock(); } }
}
