import { decideManagementAuthorization, nonDisclosingDenial } from './management-authorization.mjs';
import { appendManagementAudit, listManagementAudit, pruneManagementAudit } from './management-audit.mjs';
import { createOneTimeDisclosure, consumeOneTimeDisclosure, clearOneTimeDisclosure, generateSecretMaterial, publicCredential, safeManagementError } from './management-secrets.mjs';
import { listIntegrations, getIntegration, saveIntegration, testIntegration, integrationSnapshot, restoreIntegrationSnapshot } from './management-integrations.mjs';
import { recordWebhookAttempt, listWebhookAttempts, replayWebhookAttempt, webhookSnapshot, restoreWebhookSnapshot } from './management-webhooks.mjs';
import { explainPermissions, invite, listInvitations, updateInvitation, listMemberships, changeMembership, accessSnapshot, restoreAccessSnapshot } from './management-access.mjs';
import { managementBilling, policyPreview, confirmPolicyPreview } from './management-billing.mjs';
import { loadManagementState, saveManagementState } from './management-state.mjs';
import { randomUUID } from 'node:crypto';

const keys = new Map(); const previews = new Map();
const reauthSessions = new Map();
function freshReauthentication(actorId, token) { const session = reauthSessions.get(token); if (!session || session.actorId !== actorId || session.expiresAt < Date.now()) return false; return true; }
function response(res, status, body) { res.writeHead(status, { 'content-type': 'application/json', 'cache-control': 'no-store', 'referrer-policy': 'no-referrer', 'content-security-policy': "default-src 'none'" }); res.end(JSON.stringify(body)); return true; }
function capability(path, method) { if (path.includes('/providers')) return method === 'GET' ? 'providersRead' : 'providersWrite'; if (path.includes('/api-keys')) return method === 'GET' ? 'keysRead' : 'keysWrite'; if (path.includes('/webhooks')) return method === 'GET' ? 'webhooksRead' : 'webhooksWrite'; if (path.includes('/access')) return method === 'GET' ? 'accessRead' : 'accessWrite'; if (path.includes('/billing')) return 'billingRead'; if (path.includes('/audit')) return 'auditRead'; return method === 'GET' ? 'accessRead' : 'settingsWrite'; }
async function bodyOf(readBody, req) { try { return JSON.parse((await readBody(req)) || '{}'); } catch { return null; } }
function audit(db, decision, intent, outcome, body, classification = 'restricted') { return appendManagementAudit(db, { decision, intent, reason: body?.reason, outcome, disclosureClassification: classification, evidence: { request: body } }); }
function publicKey(row) { return publicCredential(row); }

/** Dispatch the additive /api/management contract.  Every request is authenticated and audited. */
export async function handleManagementRequest(req, res, url, { config, db, readBody, requireAuth, dashboardAuthorized = () => false }) {
  if (!url.pathname.startsWith('/api/management/')) return false;
  // The embedded local dashboard has a per-boot, same-origin server-verified session token;
  // API clients use a verified bearer/API-key identity. Neither path trusts UI-selected scope.
  if (!req.headers.authorization && dashboardAuthorized(req)) req.user = { sub: 'local-operator', role: 'admin' };
  else if (!requireAuth(req, res)) return true;
  const body = ['POST', 'PUT', 'PATCH', 'DELETE'].includes(req.method) ? await bodyOf(readBody, req) : {};
  if (body === null) return response(res, 400, { ok: false, error: { code: 'INVALID_JSON' } });
  const decision = decideManagementAuthorization({ config, user: req.user, capability: capability(url.pathname, req.method), requestedScope: { tenantId: body.tenantId ?? url.searchParams.get('tenantId'), projectId: body.projectId ?? url.searchParams.get('projectId') } });
  if (!decision.allowed) { audit(db, decision, 'management_request', 'denied', body); return response(res, 403, nonDisclosingDenial(decision)); }
  const scope = decision.scope; const path = url.pathname; const state = loadManagementState(db, scope.tenantId); keys.clear(); previews.clear(); for (const row of state.keys ?? []) keys.set(...row); for (const row of state.previews ?? []) previews.set(...row); restoreIntegrationSnapshot(state.integrations); restoreWebhookSnapshot(state.webhooks); restoreAccessSnapshot(state.access);
  pruneManagementAudit(db);
  const fail = (status, outcome, intent = 'management_request') => { const event = audit(db, decision, intent, outcome, body); return response(res, status, { ok: false, outcome, correlationId: decision.correlationId, audit: { id: event.id } }); };
  try {
    if (req.method === 'POST' && path === '/api/management/reauthenticate') {
      if (req.user.sub === 'local-operator') return fail(403, 'denied', 'reauthenticate');
      const { getUserStore } = await import('../auth/user-store.mjs'); const account = getUserStore().getUserById(req.user.sub);
      if (!account || !getUserStore().verifyCredentials(account.email, body.password)) return fail(401, 'denied', 'reauthenticate');
      const token = randomUUID(); reauthSessions.set(token, { actorId: req.user.sub, expiresAt: Date.now() + 5 * 60_000 }); const event = audit(db, decision, 'reauthenticate', 'succeeded', body);
      return response(res, 200, { ok: true, reauthToken: token, expiresAt: new Date(Date.now() + 5 * 60_000).toISOString(), correlationId: decision.correlationId, audit: { id: event.id } });
    }
    if (req.method === 'GET' && path === '/api/management/providers') { const event = audit(db, decision, 'providers_list', 'allowed', body); return response(res, 200, { ok: true, providers: listIntegrations(scope), correlationId: decision.correlationId, audit: { id: event.id } }); }
    const provider = path.match(/^\/api\/management\/providers\/([^/]+)(?:\/(test|retry))?$/);
    if (provider && req.method === 'GET' && !provider[2]) { const row = getIntegration(provider[1], scope); if (!row) return fail(404, 'denied', 'provider_read'); const event = audit(db, decision, 'provider_read', 'allowed', body); return response(res, 200, { ok: true, provider: row, correlationId: decision.correlationId, audit: { id: event.id } }); }
    if (req.method === 'POST' && path === '/api/management/providers') { const row = saveIntegration(scope, body); const event = audit(db, decision, 'provider_create', 'succeeded', body); return response(res, 201, { ok: true, provider: row, correlationId: decision.correlationId, audit: { id: event.id } }); }
    if (provider && ['POST', 'PUT', 'PATCH'].includes(req.method)) { const row = provider[2] ? await testIntegration(provider[1], scope, { retry: provider[2] === 'retry' ? 1 : 0, credential: body.credential, runner: async (integration, { signal }) => { try { const { resolveProvider } = await import('../providers.mjs'); const { testProviderConnection } = await import('../provider-conformance.mjs'); const resolved = resolveProvider(integration.provider, {}, config); return resolved?.keyEnv ? testProviderConnection(resolved, body.credential, { signal }) : { status: 'unsupported' }; } catch { return { status: 'unknown' }; } } }) : saveIntegration(scope, { ...body, id: provider[1] }); if (!row) return fail(404, 'denied', 'provider_operation'); const event = audit(db, decision, provider[2] ? `provider_${provider[2]}` : 'provider_update', row.status === 'success' ? 'succeeded' : 'failed', body); return response(res, 200, { ok: true, result: row, correlationId: decision.correlationId, audit: { id: event.id } }); }
    if (req.method === 'GET' && path === '/api/management/api-keys') { const event = audit(db, decision, 'key_list', 'allowed', body); return response(res, 200, { ok: true, keys: [...keys.values()].filter((x) => x.tenantId === scope.tenantId && (!scope.projectId || x.projectId === scope.projectId)).map(publicKey), correlationId: decision.correlationId, audit: { id: event.id } }); }
    if (req.method === 'POST' && path === '/api/management/api-keys') { const id = randomUUID(); const material = generateSecretMaterial(); const row = { id, tenantId: scope.tenantId, projectId: scope.projectId, name: String(body.name || 'API key').slice(0, 80), scopes: Array.isArray(body.scopes) ? body.scopes : [], active: true, createdAt: new Date().toISOString(), replacementFor: null }; keys.set(id, row); const disclosure = createOneTimeDisclosure({ keyId: id, material }); const event = audit(db, decision, 'key_create', 'succeeded', body, 'secret_once'); return response(res, 201, { ok: true, key: publicKey(row), disclosure: { ...disclosure, secret: material }, correlationId: decision.correlationId, audit: { id: event.id } }); }
    const keyRoute = path.match(/^\/api\/management\/api-keys\/([^/]+)(?:\/(disclose|close|rotate|revoke))?$/);
    if (keyRoute && keyRoute[2] === 'disclose' && req.method === 'POST') { const material = consumeOneTimeDisclosure(body.nonce, keyRoute[1]); if (!material) return fail(410, 'conflict', 'key_disclose'); const event = audit(db, decision, 'key_disclose', 'succeeded', body, 'secret_once'); return response(res, 200, { ok: true, disclosure: { secret: material, expiresAt: new Date().toISOString() }, correlationId: decision.correlationId, audit: { id: event.id } }); }
    if (keyRoute && keyRoute[2] === 'close' && req.method === 'POST') { clearOneTimeDisclosure(body.nonce); const event = audit(db, decision, 'key_disclosure_close', 'cancelled', body, 'secret_once'); return response(res, 204, { ok: true, correlationId: decision.correlationId, audit: { id: event.id } }); }
    if (keyRoute && keyRoute[2] === 'rotate' && req.method === 'POST') { const old = keys.get(keyRoute[1]); if (!old || old.tenantId !== scope.tenantId) return fail(404, 'denied', 'key_rotate'); const overlapMs = Math.min(86400000, Math.max(0, Number(body.overlapMs) || 3600000)); old.overlapUntil = new Date(Date.now() + overlapMs).toISOString(); const id = randomUUID(); const material = generateSecretMaterial(); const row = { ...old, id, replacementFor: old.id, createdAt: new Date().toISOString(), overlapUntil: null }; keys.set(id, row); const disclosure = createOneTimeDisclosure({ keyId: id, material }); const event = audit(db, decision, 'key_rotate', 'succeeded', body, 'secret_once'); return response(res, 201, { ok: true, key: publicKey(row), disclosure: { ...disclosure, secret: material }, previousOverlapUntil: old.overlapUntil, correlationId: decision.correlationId, audit: { id: event.id } }); }
    if (keyRoute && keyRoute[2] === 'revoke' && req.method === 'POST') { const row = keys.get(keyRoute[1]); if (!row || row.tenantId !== scope.tenantId) return fail(404, 'denied', 'key_revoke'); if (body.confirmation !== `REVOKE ${row.name}` || !freshReauthentication(req.user.sub, req.headers['x-management-reauth'])) return fail(409, 'conflict', 'key_revoke'); row.active = false; row.revokedAt = new Date().toISOString(); const event = audit(db, decision, 'key_revoke', 'succeeded', body); return response(res, 200, { ok: true, key: publicKey(row), correlationId: decision.correlationId, audit: { id: event.id } }); }
    const webhook = path.match(/^\/api\/management\/webhooks\/([^/]+)\/attempts(?:\/([^/]+)\/replay)?$/);
    if (webhook && req.method === 'GET') { const page = listWebhookAttempts(scope, webhook[1], { cursor: url.searchParams.get('cursor'), limit: url.searchParams.get('limit') }); const event = audit(db, decision, 'webhook_attempts_list', 'allowed', body); return response(res, 200, { ok: true, ...page, correlationId: decision.correlationId, audit: { id: event.id } }); }
    if (webhook && webhook[2] && req.method === 'POST') { const replay = replayWebhookAttempt(scope, webhook[1], webhook[2], body.reason); const event = audit(db, decision, 'webhook_replay', replay.outcome, body); return response(res, replay.outcome === 'denied' ? 404 : replay.outcome === 'ineligible' ? 409 : 200, { ok: replay.outcome === 'succeeded' || replay.outcome === 'duplicate', replay, correlationId: decision.correlationId, audit: { id: event.id } }); }
    if (req.method === 'POST' && path === '/api/management/webhooks/attempts') { const row = recordWebhookAttempt(scope, body); const event = audit(db, decision, 'webhook_attempt_record', 'succeeded', body); return response(res, 201, { ok: true, attempt: row, correlationId: decision.correlationId, audit: { id: event.id } }); }
    if (req.method === 'GET' && path === '/api/management/access/invitations') { const event = audit(db, decision, 'invitation_list', 'allowed', body); return response(res, 200, { ok: true, invitations: listInvitations(scope), correlationId: decision.correlationId, audit: { id: event.id } }); }
    if (req.method === 'POST' && path === '/api/management/access/invitations') { const row = invite(scope, body); const event = audit(db, decision, 'invitation_create', 'succeeded', body); return response(res, 201, { ok: true, invitation: row, correlationId: decision.correlationId, audit: { id: event.id } }); }
    const invitation = path.match(/^\/api\/management\/access\/invitations\/([^/]+)\/(resend|cancel|accept)$/);
    if (invitation && req.method === 'POST') { const row = updateInvitation(scope, invitation[1], invitation[2], body.identity); if (!row) return fail(409, invitation[2] === 'accept' ? 'conflict' : 'denied', `invitation_${invitation[2]}`); const event = audit(db, decision, `invitation_${invitation[2]}`, 'succeeded', body); return response(res, 200, { ok: true, invitation: row, correlationId: decision.correlationId, audit: { id: event.id } }); }
    if (req.method === 'GET' && path === '/api/management/access/memberships') { const event = audit(db, decision, 'membership_list', 'allowed', body); return response(res, 200, { ok: true, memberships: listMemberships(scope), correlationId: decision.correlationId, audit: { id: event.id } }); }
    if (req.method === 'GET' && path === '/api/management/access/effective-permissions') { const event = audit(db, decision, 'permissions_explain', 'allowed', body); return response(res, 200, { ok: true, permissions: explainPermissions({ ...scope, role: req.user.role }), correlationId: decision.correlationId, audit: { id: event.id } }); }
    const membership = path.match(/^\/api\/management\/access\/memberships\/([^/]+)$/);
    if (membership && req.method === 'PATCH') { const row = changeMembership(scope, membership[1], body.role); if (!row) return fail(404, 'denied', 'membership_change'); const event = audit(db, decision, 'membership_change', 'succeeded', body); return response(res, 200, { ok: true, membership: row, correlationId: decision.correlationId, audit: { id: event.id } }); }
    if (req.method === 'GET' && path === '/api/management/billing') { const event = audit(db, decision, 'billing_read', 'allowed', body); return response(res, 200, { ok: true, billing: managementBilling(scope, config), correlationId: decision.correlationId, audit: { id: event.id } }); }
    if (req.method === 'POST' && path === '/api/management/settings/policy/preview') { const preview = policyPreview(scope, body); const id = randomUUID(); previews.set(id, preview); const event = audit(db, decision, 'policy_preview', 'succeeded', body); return response(res, 200, { ok: true, preview: { id, ...preview }, correlationId: decision.correlationId, audit: { id: event.id } }); }
    const policy = path.match(/^\/api\/management\/settings\/policy\/([^/]+)\/(confirm|rollback)$/);
    if (policy && req.method === 'POST') { const preview = previews.get(policy[1]); if (!preview || preview.scope.tenantId !== scope.tenantId) return fail(404, 'denied', `policy_${policy[2]}`); if (policy[2] === 'confirm' && !freshReauthentication(req.user.sub, req.headers['x-management-reauth'])) return fail(409, 'conflict', 'policy_confirm'); const result = policy[2] === 'confirm' ? confirmPolicyPreview(preview, body) : { outcome: 'succeeded', rollbackBoundary: preview.rollbackBoundary }; const event = audit(db, decision, `policy_${policy[2]}`, result.outcome, body); return response(res, 200, { ok: true, result, correlationId: decision.correlationId, audit: { id: event.id } }); }
    if (req.method === 'GET' && path === '/api/management/audit') { const page = listManagementAudit(db, scope, { cursor: url.searchParams.get('cursor'), limit: url.searchParams.get('limit') }); return response(res, 200, { ok: true, ...page, correlationId: decision.correlationId }); }
    return response(res, 404, { ok: false, error: { code: 'MANAGEMENT_NOT_FOUND', correlationId: decision.correlationId } });
  } catch { const event = audit(db, decision, 'management_request', 'failed', body); return response(res, 500, { ok: false, error: safeManagementError(), correlationId: decision.correlationId, audit: { id: event.id } }); }
  finally { saveManagementState(db, scope.tenantId, { keys: [...keys.entries()], previews: [...previews.entries()], integrations: integrationSnapshot(), webhooks: webhookSnapshot(), access: accessSnapshot() }); }
}
