import { randomUUID } from 'node:crypto';
const invitations = new Map(); const memberships = new Map();
export function accessSnapshot() { return { invitations: [...invitations.entries()], memberships: [...memberships.entries()] }; }
export function restoreAccessSnapshot(snapshot = {}) { invitations.clear(); memberships.clear(); for (const row of snapshot.invitations ?? []) invitations.set(...row); for (const row of snapshot.memberships ?? []) memberships.set(...row); }
const PERMISSIONS = Object.freeze({ admin: ['providers:write', 'keys:write', 'webhooks:write', 'access:write', 'settings:write', 'audit:read'], operator: ['providers:read', 'webhooks:write', 'access:read', 'billing:read', 'audit:read'], viewer: [] });
export function explainPermissions({ tenantId, projectId, role = 'viewer', inheritedRole = null }) { return { tenantId, projectId, explicitRole: role, inheritedRole, allowed: PERMISSIONS[role] ?? [], denied: Object.values(PERMISSIONS).flat().filter((x) => !(PERMISSIONS[role] ?? []).includes(x)) }; }
export function invite(scope, { email, role = 'viewer' }) { const now = Date.now(); for (const row of invitations.values()) if (row.tenantId === scope.tenantId && row.projectId === scope.projectId && row.email === String(email).toLowerCase() && row.status === 'pending') { row.status = 'superseded'; row.updatedAt = new Date(now).toISOString(); } const row = { id: randomUUID(), tenantId: scope.tenantId, projectId: scope.projectId, email: String(email).toLowerCase(), role, status: 'pending', expiresAt: new Date(now + 86400000).toISOString(), version: 1, createdAt: new Date(now).toISOString() }; invitations.set(row.id, row); return { ...row }; }
export function listInvitations(scope) { return [...invitations.values()].filter((x) => x.tenantId === scope.tenantId && (!scope.projectId || x.projectId === scope.projectId)).map((x) => ({ ...x, status: x.status === 'pending' && Date.parse(x.expiresAt) <= Date.now() ? 'expired' : x.status })); }
export function updateInvitation(scope, id, action, identity) { const row = invitations.get(id); if (!row || row.tenantId !== scope.tenantId || (scope.projectId && row.projectId !== scope.projectId)) return null; if (action === 'cancel' && row.status === 'pending') row.status = 'cancelled'; else if (action === 'resend' && row.status === 'pending') return invite(scope, { email: row.email, role: row.role }); else if (action === 'accept' && row.status === 'pending' && Date.parse(row.expiresAt) > Date.now() && String(identity).toLowerCase() === row.email) { row.status = 'accepted'; memberships.set(`${scope.tenantId}:${scope.projectId}:${row.email}`, { email: row.email, role: row.role, version: 1, tenantId: scope.tenantId, projectId: scope.projectId }); } else return null; return { ...row }; }
export function listMemberships(scope) { return [...memberships.values()].filter((x) => x.tenantId === scope.tenantId && (!scope.projectId || x.projectId === scope.projectId)).map((x) => ({ ...x, effectivePermissions: explainPermissions(x) })); }
export function changeMembership(scope, email, role) { const row = memberships.get(`${scope.tenantId}:${scope.projectId}:${String(email).toLowerCase()}`); if (!row) return null; row.role = role; row.version += 1; return { ...row, effectivePermissions: explainPermissions(row) }; }
