import { test, expect } from '@playwright/test';

test('management routes exercise the real server, one-time disclosure cleanup, keyboard focus, zoom/reduced-motion and narrow viewport', async ({ page }, testInfo) => {
  const suffix = testInfo.project.name; const providerName = `openai-${suffix}`; const keyName = `Browser credential ${suffix}`; const memberEmail = `browser-member-${suffix}@example.test`;
  await page.emulateMedia({ reducedMotion: 'reduce' }); await page.goto('/app/integrations/providers');
  await expect(page.getByRole('heading', { name: 'Integrations' })).toBeVisible(); await expect(page.locator('#provider-name')).toBeVisible(); await expect(page.getByLabel('Credential')).toBeVisible(); await page.locator('#provider-name').fill(providerName); await page.locator('#provider-credential').fill('browser-transient-credential'); await page.getByRole('button', { name: 'Add provider' }).click(); await expect(page.getByRole('link', { name: providerName })).toBeVisible(); await expect(page.locator('body')).not.toContainText('browser-transient-credential');
  await page.goto('/app/integrations/api-keys'); await expect(page.getByRole('heading', { name: 'API keys' })).toBeVisible(); await page.getByLabel('Key name').fill(keyName); await page.getByRole('button', { name: 'Create API key' }).click(); await expect(page.getByRole('dialog', { name: 'One-time API key disclosure' })).toBeVisible(); const disclosed = await page.getByRole('dialog').locator('code').textContent(); expect(disclosed).toMatch(/^mk-/); await page.getByRole('button', { name: 'I stored this key' }).click(); await expect(page.getByRole('dialog')).toHaveCount(0); await expect(page.locator('body')).not.toContainText(disclosed); const keyRow = page.getByRole('row', { name: new RegExp(keyName) }); await keyRow.getByRole('button', { name: 'Revoke' }).click(); await page.locator('#management-confirmation').fill(`REVOKE ${keyName}`); await page.locator('#management-reauthentication').fill('local-session'); await page.getByRole('button', { name: 'Revoke key' }).click(); await expect(page.getByRole('row', { name: new RegExp(`${keyName}.*Revoked`) })).toBeVisible();
  await page.goto('/app/administration/members'); await expect(page.getByRole('heading', { name: 'Members and invitations' })).toBeVisible(); await page.getByLabel('Email').fill(memberEmail); await page.getByLabel('Role').selectOption('viewer'); await page.getByRole('button', { name: 'Invite member' }).click(); await expect(page.getByRole('row', { name: new RegExp(`${memberEmail}.*viewer.*pending`) })).toBeVisible();
  await page.goto('/app/administration/tenant-settings'); await page.getByRole('button', { name: 'Preview policy impact' }).click(); await expect(page.getByRole('button', { name: 'Confirm policy push' })).toBeVisible(); await page.getByRole('button', { name: 'Confirm policy push' }).click(); await page.locator('#management-confirmation').fill('APPLY POLICY'); await page.locator('#management-reauthentication').fill('local-session'); await page.getByRole('button', { name: 'Apply policy' }).click(); await expect(page.getByText('Policy outcome:')).toBeVisible();
  await page.goBack(); await expect(page.getByRole('heading', { name: 'Members and invitations' })).toBeVisible(); await page.goForward(); await expect(page.getByRole('heading', { name: 'Tenant settings and policy impact' })).toBeVisible();
  await page.setViewportSize({ width: 320, height: 800 }); await page.keyboard.press('Tab'); await expect(page.locator('.skip-link')).toBeFocused(); await page.screenshot({ path: testInfo.outputPath('management-narrow-reduced-motion.png'), fullPage: true });
});
