apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "meridianos.fullname" . }}-config
  labels:
    {{- include "meridianos.labels" . | nindent 4 }}
data:
  policy.yaml: |
{{ .Values.policy.yamlContent | indent 4 }}
